export const searchData = [
  {
    id: 1,
    subject: "Meeting Tomorrow",
    preview: "Hi, let's discuss the project details for our upcoming meeting tomorrow.",
    sender: "John Doe",
    date: "10:30 AM",
    folder: "inbox",
    read: false,
  },
  {
    id: 2,
    subject: "Project Update - Q1 2024",
    preview: "Here's the quarterly update for our ongoing projects. Please review the attached documents.",
    sender: "Sarah Wilson",
    date: "Yesterday",
    folder: "inbox",
    read: true,
  },
  {
    id: 3,
    subject: "New Design Mockups",
    preview: "I've finished the new design mockups for the mobile app. Let me know your thoughts!",
    sender: "Mike Chen",
    date: "Mar 20",
    folder: "inbox",
    read: true,
  },
  {
    id: 4,
    subject: "Team Building Event",
    preview: "Join us for our annual team building event next month. Details inside!",
    sender: "HR Department",
    date: "Mar 19",
    folder: "inbox",
    read: false,
  },
  {
    id: 5,
    subject: "Client Presentation Feedback",
    preview: "Great job on the client presentation today. Here's some feedback from the team.",
    sender: "Emily Brown",
    date: "Mar 18",
    folder: "inbox",
    read: true,
  },
];